### PR TITLE
Add Russian lang

### PR DESCRIPTION
**Pull request by vorons**

### CODE REVIEW

**Comment by imeoer** [comment]
@vorons It's cool! thanks for russian translation. ;)

**Comment by vorons** [comment]
Can You add a line for translate timeSince? /template/theme/source/js/index.coffee

**Comment by imeoer** [comment]
@vorons latest commit already translate timeSince, just modify the `config.yml` for russian support. ;)

**Comment by vorons** [comment]
cool! thanks

**Pull request merged**
